SELECT 'CREATE DATABASE incidents_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'incidents_db')\gexec
\c incidents_db;
DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backend') THEN
		CREATE USER backend WITH PASSWORD 'backend';
	END IF;
END$$;
GRANT CONNECT ON DATABASE "incidents_db" TO backend;
GRANT USAGE ON SCHEMA public TO backend;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO backend;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO backend;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO backend;

-- Grant permissions on future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO backend;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO backend;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO backend;
